# Generated by Django 4.0 on 2024-05-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Преподаватель'),
        ),
    ]
