# Generated by Django 4.0 on 2024-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_grade_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingAssignment',
        ),
    ]
