# Generated by Django 4.0 on 2024-05-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_subject_alter_schedule_options_and_more'),
        ('journal', '0005_delete_teachingassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='schedule.subject', verbose_name='Урок'),
        ),
    ]
