# Generated by Django 4.0 on 2024-05-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_grade_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='lesson',
            new_name='subject',
        ),
    ]
