# Generated by Django 4.0 on 2024-05-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_rename_lesson_grade_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='score',
            new_name='mark',
        ),
    ]
