# Generated by Django 4.0 on 2024-05-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_teachingassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingassignment',
            name='group',
        ),
    ]
