# Generated by Django 4.0 on 2024-05-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_remove_teachingassignment_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingAssignment',
        ),
    ]
