# Generated by Django 4.0 on 2024-05-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_teacher'),
        ('journal', '0011_delete_teachingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule', verbose_name='К какому уроку'),
        ),
    ]
