# Generated by Django 4.0 on 2024-05-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_teacher'),
        ('journal', '0012_grade_subject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('lesson', 'За урок'), ('session', 'За сессию')], default='lesson', max_length=10, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grades', to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule', verbose_name='Урок или сессия'),
        ),
    ]
