# Generated by Django 4.0 on 2024-05-26 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('Урок', 'Урок'), ('Сессия', 'Сессия')], max_length=10, verbose_name='Тип расписания')),
            ],
            options={
                'verbose_name': 'Тип расписания',
                'verbose_name_plural': 'Типы расписания',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предметы студентов',
                'verbose_name_plural': 'Предметы студентов',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=150, verbose_name='День недели')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.IntegerField(null=True, verbose_name='Номер пары')),
                ('time_from', models.TimeField(null=True, verbose_name='Начало пары')),
                ('time_to', models.TimeField(null=True, verbose_name='Конец пары')),
                ('type_of_lesson', models.CharField(max_length=150, null=True, verbose_name='Вид занятий')),
                ('place_of_perfomance', models.CharField(max_length=150, null=True, verbose_name='Место проведение')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.group', verbose_name='Название группы')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Название предмета')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Преподаватель')),
                ('type_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletype', verbose_name='Вид рассписания')),
            ],
            options={
                'verbose_name': 'Расписание студентов',
                'verbose_name_plural': 'Расписание студентов',
            },
        ),
    ]
