# Generated by Django 4.0 on 2024-05-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предметы студентов',
                'verbose_name_plural': 'Предметы студентов',
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание студентов', 'verbose_name_plural': 'Расписание студентов'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name_of_discipline',
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.group', verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=150, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(verbose_name='Начало пары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(verbose_name='Конец пары'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Название предмета'),
        ),
    ]
