# Generated by Django 4.0 on 2024-05-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group'),
        ('schedule', '0002_group_subject_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.group', verbose_name='Название группы'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
