# Generated by Django 4.0 on 2024-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_session_alter_scheduletype_schedule_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессия'},
        ),
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8')], max_length=10, unique=True, verbose_name='Номер сессии'),
        ),
    ]
