# Generated by Django 4.0 on 2024-05-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_sessionschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionschedule',
            options={'verbose_name': 'Расписание сессий', 'verbose_name_plural': 'Расписание сессий'},
        ),
    ]
