# Generated by Django 4.0 on 2024-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_session_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(choices=[(1, 'Первый семестр'), (2, 'Второй семестр'), (3, 'Третий семестр'), (4, 'Четвертый семестр'), (5, 'Пятый семестр'), (6, 'Шестой семестр'), (7, 'Седьмой семестр'), (8, 'Восьмой семестр')], max_length=10, unique=True, verbose_name='Номер сессии'),
        ),
    ]
