# Generated by Django 4.0 on 2024-05-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_teachingassignment'),
        ('schedule', '0006_alter_schedule_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Преподаватель'),
        ),
    ]
