# Generated by Django 4.0 on 2024-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('lesson', 'Урок'), ('session', 'Сессия')], max_length=10, verbose_name='Тип расписания')),
            ],
            options={
                'verbose_name': 'Тип расписания',
                'verbose_name_plural': 'Типы расписания',
            },
        ),
        migrations.DeleteModel(
            name='SessionSchedule',
        ),
    ]
