# Generated by Django 4.0 on 2024-05-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_scheduletype_delete_sessionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='typy_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletype'),
        ),
    ]
