# Generated by Django 4.0 on 2024-05-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_schedule_typy_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='typy_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletype', verbose_name='Вид рассписания'),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='schedule_type',
            field=models.CharField(choices=[('Урок', 'Урок'), ('Сессия', 'Сессия')], max_length=10, verbose_name='Тип расписания'),
        ),
    ]
