# Generated by Django 4.0 on 2024-05-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_schedule_typy_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(null=True, verbose_name='Начало пары'),
        ),
    ]
