# Generated by Django 4.0 on 2024-05-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Список групп', 'verbose_name_plural': 'Список групп'},
        ),
    ]
