# Generated by Django 4.0 on 2024-05-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.group', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
