# Generated by Django 4.0 on 2024-05-12 09:48

import authentication.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(authentication.enum.Groups['DECANAT'], 'Деканат'), (authentication.enum.Groups['TEACHER'], 'Преподователь'), (authentication.enum.Groups['STUDENT'], 'Студент')], default='Студент', max_length=50),
        ),
    ]
