# Generated by Django 4.0 on 2024-05-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.group', verbose_name='Группа'),
        ),
    ]
