# Generated by Django 4.0 on 2024-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DECANAT', 'Деканат'), ('TEACHER', 'Преподователь'), ('STUDENT', 'Студент')], default='Студент', max_length=50, verbose_name='Роль'),
        ),
    ]
