# Generated by Django 4.0 on 2024-05-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_teachingassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingAssignment',
        ),
    ]
